version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./docker/nging/conf.d:/etc/nginx/conf.d
      - ./docker/nging/html:/etc/nginx/html
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:lts
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   # 修改成你的密码
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

